# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_6gfRm_xNiKfRFgoGtUtyzbadVqBT2A
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="Marketing Analytics Dashboard", layout="wide")

st.title("📊 Marketing Campaign & ROAS Dashboard")
st.markdown("Filter performance metrics across acquisition channels and analyze Return on Ad Spend (ROAS).")

# 2. Synthetic Dataset Generation
@st.cache_data
def load_data():
    data = {
        'Channel': ['Google Ads', 'Meta Ads', 'Organic Search', 'Email', 'Google Ads', 'Meta Ads', 'Email'],
        'Campaign': ['Search_Brand', 'Retargeting_V1', 'SEO_Blog', 'Newsletter_Q1', 'Shopping_General', 'Lookalike_1%', 'Promo_Flash'],
        'Spend': [1200, 2500, 0, 150, 3100, 1800, 200],
        'Conversions': [85, 110, 45, 30, 140, 65, 40],
        'Revenue': [4800, 6200, 1350, 1200, 9300, 3100, 1600]
    }
    df = pd.DataFrame(data)
    df['ROAS'] = (df['Revenue'] / df['Spend']).fillna(0).round(2)
    df['CPA'] = (df['Spend'] / df['Conversions']).fillna(0).round(2)
    return df

df = load_data()

# 3. Sidebar Filters
st.sidebar.header("Filter Options")
selected_channel = st.sidebar.multiselect(
    "Select Acquisition Channel:",
    options=df['Channel'].unique(),
    default=df['Channel'].unique()
)

filtered_df = df[df['Channel'].isin(selected_channel)]

# 4. Top KPI Cards
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Spend", f"${filtered_df['Spend'].sum():,.2f}")
col2.metric("Total Revenue", f"${filtered_df['Revenue'].sum():,.2f}")
col3.metric("Total Conversions", f"{filtered_df['Conversions'].sum():,}")
col4.metric("Avg ROAS", f"{filtered_df['ROAS'].mean():.2f}x")

st.markdown("---")

# 5. Interactive Charts
left_chart, right_chart = st.columns(2)

with left_chart:
    st.subheader("Revenue by Channel")
    fig_bar = px.bar(
        filtered_df,
        x='Channel',
        y='Revenue',
        color='Channel',
        text_auto='.2s'
    )
    st.plotly_chart(fig_bar, use_container_width=True)

with right_chart:
    st.subheader("Spend vs. Revenue (ROAS)")
    fig_scatter = px.scatter(
        filtered_df,
        x='Spend',
        y='Revenue',
        size='Conversions',
        color='Channel',
        hover_name='Campaign'
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

# 6. Data Table View & Export
st.subheader("Campaign Performance Breakdown")
st.dataframe(filtered_df, use_container_width=True)

csv_data = filtered_df.to_csv(index=False).encode('utf-8')
st.download_button(
    label="📥 Download Cleaned Report CSV",
    data=csv_data,
    file_name="marketing_performance_report.csv",
    mime="text/csv"
)